name: sber_id
description: "Flutter plugin for Sber ID authentication with native iOS SDK integration. Provides seamless authentication flow, automatic app detection, and comprehensive setup validation for iOS applications."
version: 0.0.1+1
homepage: https://github.com/nurullohabduvohidov/sber_id
repository: https://github.com/nurullohabduvohidov/sber_id

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.sber_id
        pluginClass: SberIdPlugin
      ios:
        pluginClass: SberIdPlugin